import { NextResponse } from "next/server";

const users = [
  {
    id: 1,
    name: "Taguemount Myassa",
    email: "myassa@example.com",
    joined: "Mar 1, 2023",
    events: 2,
    candidates: 7,
    role: "Selector RH",
    roleType: "selector",
  },
  {
    id: 2,
    name: "Azrou Souhila",
    email: "souhila@example.com",
    joined: "Jan 26, 2023",
    events: 3,
    candidates: 3,
    role: "Selector RH",
    roleType: "selector",
  },
  {
    id: 3,
    name: "Ben Yahia Nassim",
    email: "nassim@example.com",
    joined: "Feb 18, 2023",
    events: 5,
    candidates: 1,
    role: "DEV",
    roleType: "dev",
  },
  {
    id: 4,
    name: "Bouyakoub Hadil",
    email: "hadil@example.com",
    joined: "Feb 12, 2023",
    events: 2,
    candidates: 5,
    role: "DEV",
    roleType: "dev",
  },
  {
    id: 5,
    name: "Hamid Maroua",
    email: "maroua@example.com",
    joined: "Dec 17, 2025",
    events: 1,
    candidates: 5,
    role: "Selector RH",
    roleType: "selector",
  },
  {
    id: 6,
    name: "Saoula Lina",
    email: "lina@example.com",
    joined: "Mar 13, 2024",
    events: 3,
    candidates: 1,
    role: "DEV",
    roleType: "dev",
  },
  {
    id: 7,
    name: "Meddah Mohammed",
    email: "mohammed@example.com",
    joined: "Mar 18, 2024",
    events: 4,
    candidates: 1,
    role: "Selector RH",
    roleType: "selector",
  },
  {
    id: 8,
    name: "Meddah Mohammed",
    email: "mohammed2@example.com",
    joined: "Mar 18, 2024",
    events: 4,
    candidates: 1,
    role: "Selector RH",
    roleType: "selector",
  },
  {
    id: 9,
    name: "Meddah Mohammed",
    email: "mohammed3@example.com",
    joined: "Mar 18, 2024",
    events: 4,
    candidates: 1,
    role: "Selector RH",
    roleType: "selector",
  },
];

export async function GET() {
  return NextResponse.json(users);
}